/**
 * Detection data, frame sources, buffering, cold storage, and retention APIs.
 *
 * @module Detections
 */

export {
  createArrayDetectionFrameSource,
  createBrowserColdDetectionFrameStore,
  createBufferedDetectionTimeline,
  createChunkedDetectionFrameSource,
  createColdDetectionFrameSource,
  createCompositeDetectionFrameSource,
  createMemoryColdDetectionFrameStore,
  createProjectedDetectionFrameSource,
  createWritableDetectionFrameSource,
  projectDetectionFrame,
  projectDetectionFrames,
  DetectionBufferStatus,
  DetectionFrameRetentionMode,
  DetectionFrameSelectionMode,
  DetectionMaskEncoding,
  KeypointVisibility,
  type BufferedDetectionTimeline,
  type ColdDetectionFrameStore,
  type ColdDetectionFrameStoreLoadOptions,
  type ColdDetectionFrameStorePruneOptions,
  type ColdDetectionFrameStoreWriteOptions,
  type ColdDetectionFrameStoreWriteSummary,
  type CompressedRleDetectionMask,
  type ChunkedDetectionFrameSourceOptions,
  type CompositeDetectionFrameSourceEntry,
  type CompositeDetectionFrameSourceOptions,
  type Detection,
  type DetectionBufferOptions,
  type DetectionCoordinateSpace,
  type DetectionBufferPrepareOptions,
  type DetectionBufferState,
  type DetectionFrame,
  type DetectionFrameChunk,
  type DetectionFrameChunkDescriptor,
  type DetectionFrameChunkFetch,
  type DetectionFrameChunkManifest,
  type DetectionFrameLiveOptions,
  type DetectionFrameRetentionOptions,
  type DetectionFrameSelectionOptions,
  type DetectionFrameSource,
  type DetectionFrameSourceChanges,
  type DetectionFrameSourceVersionRange,
  type DetectionMask,
  type DetectionPlaybackGateOptions,
  type DetectionTimelineContext,
  type KeypointEdge,
  type KeypointGeometry,
  type LiveWritableDetectionFrameSource,
  type Point,
  type PolygonGeometry,
  type PolylineGeometry,
  type Rect,
  type SkeletonDefinition,
  type SkeletonDefinitions,
  type SkeletonEdgeDefinition,
  type SkeletonVertexDefinition,
  type TopLeftRect,
  type WritableDetectionFrameSource,
  type WritableDetectionFrameSourceOptions,
} from "supervision";
