/**
 * Detection data, frame sources, buffering, cold storage, and retention APIs.
 *
 * @module Detections
 */

export {
  createArrayDetectionFrameSource,
  createBrowserColdDetectionFrameStore,
  createBufferedDetectionTimeline,
  createChunkedDetectionFrameSource,
  createColdDetectionFrameSource,
  createCompositeDetectionFrameSource,
  createMemoryColdDetectionFrameStore,
  createWritableDetectionFrameSource,
  DetectionBufferStatus,
  DetectionFrameRetentionMode,
  DetectionFrameSelectionMode,
  DetectionMaskEncoding,
  KeypointVisibility,
  type BufferedDetectionTimeline,
  type ColdDetectionFrameStore,
  type ColdDetectionFrameStoreLoadOptions,
  type ColdDetectionFrameStoreWriteOptions,
  type ColdDetectionFrameStoreWriteSummary,
  type CompressedRleDetectionMask,
  type ChunkedDetectionFrameSourceOptions,
  type CompositeDetectionFrameSourceEntry,
  type CompositeDetectionFrameSourceOptions,
  type Detection,
  type DetectionBufferOptions,
  type DetectionBufferPrepareOptions,
  type DetectionBufferState,
  type DetectionFrame,
  type DetectionFrameChunk,
  type DetectionFrameChunkDescriptor,
  type DetectionFrameChunkFetch,
  type DetectionFrameChunkManifest,
  type DetectionFrameRetentionOptions,
  type DetectionFrameSelectionOptions,
  type DetectionFrameSource,
  type DetectionFrameSourceVersionRange,
  type DetectionMask,
  type DetectionPlaybackGateOptions,
  type DetectionTimelineContext,
  type KeypointEdge,
  type KeypointGeometry,
  type Point,
  type PolygonGeometry,
  type PolylineGeometry,
  type Rect,
  type SkeletonDefinition,
  type SkeletonDefinitions,
  type SkeletonEdgeDefinition,
  type SkeletonVertexDefinition,
  type TopLeftRect,
  type WritableDetectionFrameSource,
} from "supervision-js";
