/**
 * Advanced annotation editing, geometry conversion, and browser mask-brush
 * APIs available from the `supervision-js/editing` entrypoint.
 *
 * Hosts own persistence and undo/redo. The session routes gestures and renders
 * previews but never writes application data.
 *
 * @module Editing
 */

export {
  AnnotationFrameMutationKind,
  AnnotationGeometryKind,
  AnnotationGestureStateKind,
  AnnotationHandleKind,
  DetectionMaskPayloadFormat,
  MaskBrushMode,
  applyAnnotationHandleDrag,
  centerRectToTopLeftRect,
  computeDetectionMaskRect,
  computeMaskBounds,
  convertDetectionBoxToMask,
  convertDetectionBoxToPolygon,
  convertDetectionMaskToBox,
  convertDetectionMaskToPolygon,
  convertDetectionPolygonToBox,
  convertDetectionPolygonToMask,
  createAnnotationEditingEngine,
  createEditableAnnotationFrameSession,
  createMaskBrushEditor,
  decodeDetectionMaskPayload,
  deleteAnnotationVertex,
  detectMaskBorders,
  distanceToSegment,
  encodeBinaryMask,
  encodeCompressedRleCounts,
  encodeDetectionMaskPayload,
  extractMaskContour,
  extractMaskRectRuns,
  getAnnotationHandles,
  isDeflatedBase64DetectionMaskPayload,
  mergeDetectionMasks,
  mergeDetectionPolygonsByClass,
  offsetDetection,
  pickAnnotationHandle,
  pointInPolygon,
  polygonArea,
  polygonToRect,
  rasterizePolygonToMask,
  rasterizeRectToMask,
  rectToPolygon,
  topLeftRectToCenterRect,
  type AnnotationCreationTool,
  type AnnotationEditingEngine,
  type AnnotationEditingEngineOptions,
  type AnnotationEditingPreviewStyleContext,
  type AnnotationEditingState,
  type AnnotationFrameMutation,
  type AnnotationFrameMutationListener,
  type AnnotationHandleDefinition,
  type AnnotationOverlayStyle,
  type AnnotationPointerInput,
  type DetectionId,
  type DetectionMaskCompressionCodec,
  type EditableAnnotationFrameSession,
  type EditableDetection,
  type MaskBrushEditor,
  type MaskBrushPreviewOptions,
  type MaskRectRun,
  type MediaDimensions,
  type PreviewOverlayData,
  type PreviewOverlayPoint,
} from "supervision-js/editing";
