/**
 * Media probing, preparation, normalization, and decoded source APIs.
 *
 * @module Media Preparation
 */

export {
  ConversionFrameEffect,
  createImageUrlMediaSource,
  createStaticImageMediaSource,
  DEFAULT_NORMALIZATION_FRAME_RATE,
  describeConversionFrameEffect,
  evaluateMediaConditions,
  MediaConditionCode,
  MediaConditionResponse,
  MediaConditionScope,
  MediaIndexPlacement,
  MediaNormalizationAudioCodec,
  MediaNormalizationContainer,
  MediaNormalizationFit,
  MediaNormalizationVideoCodec,
  MediaPreparationError,
  MediaProbeIssueCode,
  MediaProbeStatus,
  normalizeMedia,
  normalizeMediaProgressively,
  openVideoEngineMediaSource,
  prepareMedia,
  prepareMediaProgressively,
  probeMedia,
  probeMediaConditions,
  readIndexPlacement,
  summarizeTiming,
  type ConversionFrameEffectReport,
  type DecodedMediaSource,
  type DecodedMediaSourceMetadata,
  type DecodedVideoSample,
  type DecodedVideoSampleSink,
  type DisposableMediaInput,
  type HostFrameSource,
  type PresentedFrameChannel,
  type PresentedFrameChannelSignal,
  type PresentedFrameChannelStatus,
  type PresentedFramePlayhead,
  type PresentedFrameSeekIntent,
  type PresentedFrameSource,
  type MediaNormalizationAudioOptions,
  type MediaNormalizationInputMetadata,
  type MediaNormalizationOptions,
  type MediaNormalizationOutputProgress,
  type MediaNormalizationProgress,
  type MediaNormalizationVideoOptions,
  type MediaByteReader,
  type MediaCondition,
  type MediaConditionFacts,
  type MediaConditionPolicy,
  type MediaConditionProbeOptions,
  type MediaConditionReport,
  type MediaContainerFacts,
  type MediaFrameMetadata,
  type MediaTimingFacts,
  type MediaPreparationOptions,
  type MediaTimelineMetadata,
  type MediaProbeIssue,
  type MediaProbeOptions,
  type MediaProbeResult,
  type MediaProbeTargetProfile,
  type MediaProbeVideoTrack,
  type NormalizedMedia,
  type PlatformMediaFrame,
  type PlatformMediaFrameSource,
  type PreparedMedia,
  type ProgressivePreparedMedia,
  type ProgressiveNormalizedMedia,
  type StaticImageSource,
  type VideoEngineMediaSource,
  type VideoEngineMediaSourceOptions,
} from "supervision";
