/**
 * Media probing, preparation, normalization, and decoded source APIs.
 *
 * @module Media Preparation
 */

export {
  createImageUrlMediaSource,
  createStaticImageMediaSource,
  DEFAULT_NORMALIZATION_FRAME_RATE,
  MediaNormalizationAudioCodec,
  MediaNormalizationContainer,
  MediaNormalizationFit,
  MediaNormalizationVideoCodec,
  MediaPreparationError,
  MediaProbeIssueCode,
  MediaProbeStatus,
  normalizeMedia,
  normalizeMediaProgressively,
  openWebVideoEngineMediaSource,
  prepareMedia,
  prepareMediaProgressively,
  probeMedia,
  type DecodedMediaSource,
  type DecodedMediaSourceMetadata,
  type DecodedVideoSample,
  type DecodedVideoSampleSink,
  type DisposableMediaInput,
  type HostFrameSource,
  type PresentedFrameChannel,
  type PresentedFrameChannelSignal,
  type PresentedFrameChannelStatus,
  type PresentedFrameId,
  type PresentedFramePlayhead,
  type PresentedFrameSeekIntent,
  type PresentedFrameSource,
  type PresentedVideoFrame,
  type MediaNormalizationAudioOptions,
  type MediaNormalizationInputMetadata,
  type MediaNormalizationOptions,
  type MediaNormalizationOutputProgress,
  type MediaNormalizationProgress,
  type MediaNormalizationVideoOptions,
  type MediaFrameMetadata,
  type MediaPreparationOptions,
  type MediaTimelineMetadata,
  type MediaProbeIssue,
  type MediaProbeOptions,
  type MediaProbeResult,
  type MediaProbeTargetProfile,
  type MediaProbeVideoTrack,
  type NormalizedMedia,
  type PlatformMediaFrame,
  type PlatformMediaFrameSource,
  type PreparedMedia,
  type ProgressivePreparedMedia,
  type ProgressiveNormalizedMedia,
  type StaticImageSource,
  type WebVideoEngineMediaSource,
  type WebVideoEngineMediaSourceOptions,
} from "supervision";
