/**
 * Media probing, preparation, normalization, and decoded source APIs.
 *
 * @module Media Preparation
 */

export {
  createImageUrlMediaSource,
  createStaticImageMediaSource,
  MediaNormalizationAudioCodec,
  MediaNormalizationContainer,
  MediaNormalizationFit,
  MediaNormalizationVideoCodec,
  MediaPreparationError,
  MediaProbeIssueCode,
  MediaProbeStatus,
  normalizeMedia,
  normalizeMediaProgressively,
  prepareMedia,
  prepareMediaProgressively,
  probeMedia,
  type DecodedMediaSource,
  type DecodedMediaSourceMetadata,
  type DecodedVideoSample,
  type DecodedVideoSampleSink,
  type DisposableMediaInput,
  type HostFrameSource,
  type MediaNormalizationAudioOptions,
  type MediaNormalizationInputMetadata,
  type MediaNormalizationOptions,
  type MediaNormalizationOutputProgress,
  type MediaNormalizationProgress,
  type MediaNormalizationVideoOptions,
  type MediaFrameMetadata,
  type MediaPreparationOptions,
  type MediaTimelineMetadata,
  type MediaProbeIssue,
  type MediaProbeOptions,
  type MediaProbeResult,
  type MediaProbeTargetProfile,
  type MediaProbeVideoTrack,
  type NormalizedMedia,
  type PlatformMediaFrame,
  type PlatformMediaFrameSource,
  type PreparedMedia,
  type ProgressivePreparedMedia,
  type ProgressiveNormalizedMedia,
  type StaticImageSource,
} from "supervision-js";
