/**
 * Box, mask, label, interaction, and focus style APIs used by renderer layers.
 *
 * @module Styles
 */

export {
  BaseBoxStyle,
  BaseFocusStyle,
  BaseInteractionStyle,
  BaseLabelStyle,
  BaseMaskStyle,
  BoxShape,
  BoxStrokeAlignment,
  DetectionInteractionState,
  FocusTargetMode,
  type BaseBoxStyleOptions,
  type BaseFocusStyleOptions,
  type BaseInteractionStyleOptions,
  type BaseLabelStyleOptions,
  type BaseMaskStyleOptions,
  type BoxDrawInstruction,
  type BoxFillStyle,
  type BoxStrokeStyle,
  type BoxStyle,
  type BoxStyleContext,
  type DetectionStylePredicate,
  type DetectionStyleValue,
  type FocusDrawInstruction,
  type FocusFallbackStyle,
  type FocusFillStyle,
  type FocusStyle,
  type FocusStyleContext,
  type FocusStyleValue,
  type InteractionPresentation,
  type InteractionStyle,
  type InteractionStyleContext,
  type LabelBackgroundStyle,
  type LabelDrawInstruction,
  type LabelOffsetStyle,
  LabelPlacement,
  type LabelStyle,
  type LabelStyleContext,
  type LabelTextStyle,
  type MaskDrawInstruction,
  MaskRenderMode,
  type MaskStrokeStyle,
  type MaskStrokeStyleOptions,
  type MaskStyle,
  type MaskStyleContext,
} from "supervision-js";
