/**
 * Annotation renderer descriptors plus box, mask, label, interaction, and
 * focus style APIs.
 *
 * @module Styles
 */

export {
  BaseBoxStyle,
  BaseFocusStyle,
  BaseInteractionStyle,
  BaseKeypointStyle,
  BaseLabelStyle,
  BaseMaskStyle,
  BasePolygonStyle,
  BasePolylineStyle,
  BoxShape,
  BoxStrokeAlignment,
  DEFAULT_DETECTION_CLASS_STYLES,
  DEFAULT_DETECTION_COLOR_SEQUENCE,
  DetectionInteractionState,
  FocusTargetMode,
  KeypointMarkerShape,
  LabelVisibilityMode,
  SUPERVISION_ROBOFLOW_COLOR,
  annotationRendererKinds,
  annotationRenderers,
  createDefaultAnnotationPresentation,
  normalizeDetectionClassName,
  resolveDetectionClassColorStyle,
  type BaseBoxStyleOptions,
  type BaseFocusStyleOptions,
  type BaseInteractionStyleOptions,
  type BaseKeypointStyleOptions,
  type BaseLabelStyleOptions,
  type BaseMaskStyleOptions,
  type BasePolygonStyleOptions,
  type BasePolylineStyleOptions,
  type AnnotationRenderer,
  type AnnotationRendererFactory,
  type AnnotationRendererKind,
  type BoxAnnotationRenderer,
  type DefaultAnnotationPresentationOptions,
  type BoxDrawInstruction,
  type BoxFillStyle,
  type BoxStrokeStyle,
  type BoxStyle,
  type BoxStyleContext,
  type DetectionStylePredicate,
  type DetectionStyleValue,
  type DetectionClassColorStyle,
  type FocusDrawInstruction,
  type FocusFallbackStyle,
  type FocusFillStyle,
  type FocusStyle,
  type FocusStyleContext,
  type FocusStyleValue,
  type InteractionPresentation,
  type InteractionStyle,
  type InteractionStyleContext,
  type KeypointDrawInstruction,
  type KeypointAnnotationRenderer,
  type KeypointEdgeDrawInstruction,
  type KeypointMarkerDrawInstruction,
  type KeypointStyle,
  type KeypointStyleContext,
  type LabelBackgroundStyle,
  type LabelAnnotationRenderer,
  type LabelDrawInstruction,
  type LabelOffsetStyle,
  LabelPlacement,
  type LabelStyle,
  type LabelStyleContext,
  type LabelTextStyle,
  type MaskDrawInstruction,
  type MaskAnnotationRenderer,
  MaskRenderMode,
  type MaskStrokeStyle,
  type MaskStrokeStyleOptions,
  type MaskStyle,
  type MaskStyleContext,
  type PolygonDrawInstruction,
  type PolygonAnnotationRenderer,
  type PolygonStyle,
  type PolygonStyleContext,
  type PolylineDrawInstruction,
  type PolylineAnnotationRenderer,
  type PolylineStyle,
  type PolylineStyleContext,
} from "supervision";
