/**
 * Box, mask, label, interaction, and focus style APIs used by renderer layers.
 *
 * @module Styles
 */

export {
  BaseBoxStyle,
  BaseFocusStyle,
  BaseInteractionStyle,
  BaseKeypointStyle,
  BaseLabelStyle,
  BaseMaskStyle,
  BasePolygonStyle,
  BasePolylineStyle,
  BoxShape,
  BoxStrokeAlignment,
  DEFAULT_DETECTION_CLASS_STYLES,
  DEFAULT_DETECTION_COLOR_SEQUENCE,
  DetectionInteractionState,
  FocusTargetMode,
  KeypointMarkerShape,
  LabelVisibilityMode,
  MarkerShape,
  MarkerSizeSpace,
  SUPERVISION_ROBOFLOW_COLOR,
  ShapeInstructionKind,
  createDefaultAnnotationPresentation,
  normalizeDetectionClassName,
  resolveDetectionClassColorStyle,
  resolveMarkerGeometry,
  sampleEllipseArc,
  type BaseBoxStyleOptions,
  type BaseFocusStyleOptions,
  type BaseInteractionStyleOptions,
  type BaseKeypointStyleOptions,
  type BaseLabelStyleOptions,
  type BaseMaskStyleOptions,
  type BasePolygonStyleOptions,
  type BasePolylineStyleOptions,
  type DefaultAnnotationPresentationOptions,
  type BoxDrawInstruction,
  type BoxFillStyle,
  type BoxStrokeStyle,
  type BoxStyle,
  type BoxStyleContext,
  type DetectionStylePredicate,
  type DetectionStyleValue,
  type DetectionClassColorStyle,
  type FocusDrawInstruction,
  type FocusFallbackStyle,
  type FocusFillStyle,
  type FocusStyle,
  type FocusStyleContext,
  type FocusStyleValue,
  type InteractionPresentation,
  type InteractionStyle,
  type InteractionStyleContext,
  type KeypointDrawInstruction,
  type KeypointEdgeDrawInstruction,
  type KeypointMarkerDrawInstruction,
  type KeypointStyle,
  type KeypointStyleContext,
  type LabelBackgroundStyle,
  type LabelDrawInstruction,
  type LabelOffsetStyle,
  LabelPlacement,
  type LabelStyle,
  type LabelStyleContext,
  type LabelTextStyle,
  type MaskDrawInstruction,
  MaskRenderMode,
  type MaskStrokeStyle,
  type MaskStrokeStyleOptions,
  type MaskStyle,
  type MaskStyleContext,
  type PolygonDrawInstruction,
  type PolygonStyle,
  type PolygonStyleContext,
  type PolylineDrawInstruction,
  type PolylineStyle,
  type PolylineStyleContext,
  type EllipseShapeInstruction,
  type MarkerShapeInstruction,
  type PathShapeInstruction,
  type ShapeDrawInstruction,
  type ShapeStyle,
  type ShapeStyleContext,
} from "supervision";
