export const DEFAULT_UPLOAD_CLASS_NAMES =
  "white team player\nyellow team player\nbasketball";

export const BASKETBALL_DETECTION_BUFFER_AHEAD_SECONDS = 10;
export const BASKETBALL_DETECTION_BUFFER_BEHIND_SECONDS = 0.5;
export const BASKETBALL_DETECTION_BUFFER_REFRESH_SECONDS = 0.5;
export const BASKETBALL_MASK_FRAME_CACHE_SECONDS = 5;
export const BASKETBALL_MASK_FRAME_MAX_PENDING_COUNT = 24;
export const BASKETBALL_MASK_FRAME_PREFETCH_SECONDS = 5;
export const BASKETBALL_MASK_FRAME_SCAN_INTERVAL_SECONDS = 0.1;
export const BASKETBALL_MASK_FRAME_SCHEDULE_BATCH_SIZE = 16;
export const BASKETBALL_MASK_FRAME_WORKER_COUNT = 4;
export const UPLOAD_DETECTION_CHUNK_SECONDS = 1;
export const UPLOAD_PREDICTION_PLAYBACK_GATE_SECONDS = 2;
