export enum RenderEnginePreference {
  WebGL = "webgl",
}

export const ALREADY_PRESENTED_SAMPLE_EPSILON_SECONDS = 1e-6;
export const DEFAULT_BOX_STROKE_ALPHA = 1;
export const DEFAULT_BOX_STROKE_COLOR = 0x00ff66;
export const DEFAULT_BOX_STROKE_WIDTH = 2;
export const DEFAULT_RENDER_PREPARATION_GATE_MAX_WAIT_SECONDS = 2;
export const DEFAULT_RENDER_PREPARATION_GATE_RESUME_MARGIN_WALL_SECONDS = 0.2;
export const DEFAULT_RENDER_PREPARATION_GATE_STOP_BELOW_WALL_SECONDS = 0.1;
export const RENDER_ENGINE_PREFERENCE = RenderEnginePreference.WebGL;
