/**
 * Advanced annotation editing APIs. These remain renderer-neutral except for
 * the browser canvas mask brush; hosts own persistence and undo.
 */
export {
  AnnotationFrameMutationKind,
  AnnotationGeometryKind,
  AnnotationGestureStateKind,
  AnnotationHandleKind,
  DetectionMaskPayloadFormat,
  applyAnnotationHandleDrag,
  centerRectToTopLeftRect,
  computeDetectionMaskRect,
  computeMaskBounds,
  convertDetectionBoxToMask,
  convertDetectionBoxToPolygon,
  convertDetectionMaskToBox,
  convertDetectionMaskToPolygon,
  convertDetectionPolygonToBox,
  convertDetectionPolygonToMask,
  createAnnotationEditingEngine,
  createEditableAnnotationFrameSession,
  decodeDetectionMaskPayload,
  deleteAnnotationVertex,
  detectMaskBorders,
  distanceToSegment,
  encodeBinaryMask,
  encodeCompressedRleCounts,
  encodeDetectionMaskPayload,
  extractMaskContour,
  extractMaskRectRuns,
  getAnnotationHandles,
  isDeflatedBase64DetectionMaskPayload,
  mergeDetectionMasks,
  mergeDetectionPolygonsByClass,
  offsetDetection,
  pickAnnotationHandle,
  pointInPolygon,
  polygonArea,
  polygonToRect,
  rasterizePolygonToMask,
  rasterizeRectToMask,
  rectToPolygon,
  topLeftRectToCenterRect,
} from "supervision-js-core";
export type {
  AnnotationCreationTool,
  AnnotationEditingEngine,
  AnnotationEditingEngineOptions,
  AnnotationEditingState,
  AnnotationFrameMutation,
  AnnotationFrameMutationListener,
  AnnotationHandleDefinition,
  AnnotationOverlayStyle,
  AnnotationPointerInput,
  DetectionId,
  EditableDetection,
  DetectionMaskCompressionCodec,
  EditableAnnotationFrameSession,
  MaskRectRun,
  MediaDimensions,
  PreviewOverlayData,
  PreviewOverlayPoint,
} from "supervision-js-core";
export {
  MaskBrushMode,
  createMaskBrushEditor,
  type MaskBrushEditor,
  type MaskBrushPreviewOptions,
} from "#editing/mask-brush-editor";
