#!/usr/bin/env python3
"""Write the depth renderer's 256-entry colour tables from matplotlib.

matplotlib ships each of these maps as its published 256-entry table
(`matplotlib/_cm_listed.py`), so no resampling or curve fit is involved. Turbo
is Google's table verbatim. Each channel is rounded half up to 8 bits.

    python tools/depth-colormaps/generate-depth-colormap-tables.py \
      > packages/core/src/utils/depth-colormap-tables.ts
    npx prettier --write packages/core/src/utils/depth-colormap-tables.ts
"""

import matplotlib

NAMES = ("turbo", "viridis", "cividis", "inferno", "magma")
ENTRIES_PER_LINE = 16

NOTICES = {
    "turbo": (
        "Turbo, Anton Mikhailov's published table.\n"
        "Copyright 2019 Google LLC.\n"
        "SPDX-License-Identifier: Apache-2.0\n"
        "https://gist.github.com/mikhailov-work/ee72ba4191942acecc03fe6da94fc73f"
    ),
    "viridis": (
        "Viridis, by Stéfan van der Walt, Nathaniel Smith and Eric Firing.\n"
        "Released under CC0: https://github.com/BIDS/colormap"
    ),
    "cividis": (
        "Cividis, Nuñez, Anderton and Renslow, PLOS ONE 13(7) e0199239 (2018),\n"
        "from https://github.com/pnnl/cmaputil as shipped by matplotlib.\n"
        "Copyright (c) 2017, Battelle Memorial Institute. Redistributed under\n"
        "its BSD-style licence, which asks for this notice to be kept."
    ),
    "inferno": (
        "Inferno, by Stéfan van der Walt and Nathaniel Smith.\n"
        "Released under CC0: https://github.com/BIDS/colormap"
    ),
    "magma": (
        "Magma, by Stéfan van der Walt and Nathaniel Smith.\n"
        "Released under CC0: https://github.com/BIDS/colormap"
    ),
}


def rows(name: str) -> list[str]:
    cmap = matplotlib.colormaps[name]
    if cmap.N != 256:
        raise SystemExit(f"{name} has {cmap.N} entries, not 256")
    rgb = (cmap(range(256))[:, :3] * 255 + 0.5).astype(int)
    hex_entries = [f"{r:02x}{g:02x}{b:02x}" for r, g, b in rgb]
    return [
        "".join(hex_entries[start : start + ENTRIES_PER_LINE])
        for start in range(0, 256, ENTRIES_PER_LINE)
    ]


def main() -> None:
    print(
        "// Generated by tools/depth-colormaps/generate-depth-colormap-tables.py"
    )
    print(f"// from matplotlib {matplotlib.__version__}. Do not edit by hand.")
    print("//")
    print("// Each table is 256 sRGB entries as 6-digit hex, darkest or coldest")
    print("// first, in the order the colour coordinate t runs from 0 to 1.")
    for name in NAMES:
        print()
        print("/*!")
        for line in NOTICES[name].splitlines():
            print(f" * {line}")
        print(" */")
        print(f"export const {name}Table = [")
        for row in rows(name):
            print(f'  "{row}",')
        print('].join("");')


if __name__ == "__main__":
    main()
